//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropBagLib.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EmitProxy")]
        public global::DRM.PropBag.AutoMapperSupport.PropBagMappingStrategyEnum MappingStrategy {
            get {
                return ((global::DRM.PropBag.AutoMapperSupport.PropBagMappingStrategyEnum)(this["MappingStrategy"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DRM.PropBag.AutoMapperSupport.MapperConfigurationProvider MapperConfigurationProvider {
            get {
                return ((global::DRM.PropBag.AutoMapperSupport.MapperConfigurationProvider)(this["MapperConfigurationProvider"]));
            }
            set {
                this["MapperConfigurationProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DRM.PropBag.ViewModelBuilder.DefaultModuleBuilderInfoProvider ModuleBuilderInfoProvider {
            get {
                return ((global::DRM.PropBag.ViewModelBuilder.DefaultModuleBuilderInfoProvider)(this["ModuleBuilderInfoProvider"]));
            }
            set {
                this["ModuleBuilderInfoProvider"] = value;
            }
        }
    }
}
